### ISSUE TITLE
Suchfunktion

### ISSUE THREAD

**Issue by ghost** [letsgamedev/gamesengine#19]
Ich denke es wäre doch eine nützlich Funktion eine eingebaute Suchfunktion zu haben, nicht jeder nutzt STRG + F zum suchen ;) Nur mal so als kleine Anregung, falls jemand Lust hat so etwas zu coden

**Comment by letsgamedev** [comment]
Ja die Suchfunktion wird in den nächsten Tag super fesch eingebaut.
