### ISSUE TITLE
Crysis 1/2 Engines

### ISSUE THREAD

**Issue by Mat2095** [letsgamedev/gamesengine#45]
The original Crysis for PC was not made with CryEngine 1 but CryEngine 2 and the Console-Versions were made later with CryEngine 3. (I don't know how to put multiple Engines in the table, so I'm making an issue)
Crysis 2 was made with CryEngine 3, not CryEngine 2.
Crysis 3 being made with CryEngine 3 is correct tough.

**Comment by AnnsAnns** [comment]
Pull Request #52 sent 😄

**Comment by letsgamedev** [comment]
done
