### ISSUE TITLE
Frostbite Games

### ISSUE THREAD

**Issue by tobimori** [letsgamedev/gamesengine#46]
Some Frostbite Games are Made with the Ignite Engine on older Platforms like FIFA on PS3/X360

**Comment by AnnsAnns** [comment]
Impossible to fix as the website was made to only allow 1 engine per game

**Comment by Mat2095** [comment]
Well, the website could be improved to support multiple engines, maybe even noting the platforms. Since there are multiple games that use more than one engine, I think it would be a good idea to add this feature.

**Comment by AnnsAnns** [comment]
as much as I have to agree, it isn't worth it. This project is sadly in its dying state right now and won't (as long as Tom has to work as much as he currently has to) be revived

**Comment by lorisleitner** [comment]
I think Tom should pick some people from the community and grant them write access on this repository. I really like this project and it's sad that it has not been updated for a long time.

**Comment by AnnsAnns** [comment]
Yeah, that would probably revive the project

EDIT: I wrote him a message on discord, let's hope that he will react

**Comment by letsgamedev** [comment]
Its now possible to add multiply engines per game. We have to use a special syntax for that kind of games:
  {name: 'TEST', engine: {PC: COCOS2DX, PS3: UNITY, WIIU: FROSTBITE}, releaseDate: {d: 2, m: 8, y: 2013}, imgId: 'geometrydash', yt: 'ELeCcv11zXE'}

so the engine will become an object for such games. The platform names are "free" but please write them in upper case.
