### ISSUE TITLE
Plattform als weitere Kategorie

### ISSUE THREAD

**Issue by StudioNameHere** [letsgamedev/gamesengine#8]
Eventuell wäre es hilfreich, die jeweiligen Plattformen zusätzlich anzugeben, um z.B. zu sehen welche Engine vermehrt auf welcher Plattform genutzt wird.

**Comment by letsgamedev** [comment]
Daran dachte ich auch schon, erhöht die Komplexität zu sehr. Da nicht jeder Enigne zu all den angegeben Plattformen passen wie bei Minecraft zum Beispiel. Darum ist eher immer die Ursprungsengine anzugeben. und dann könnte man bei einer Engineübersicht angeben zu welchen Plattformen sich das exportieren lässt.
