### ISSUE TITLE
Spiele als JSON Datein

### ISSUE THREAD

**Issue by felixkraas** [letsgamedev/gamesengine#9]
Wäre es nicht leichter Spiele als JSON Datei hinzuzufügen?
Also nach dem Schema:
/Root
   ./img
  ./games
      ./games/TollesSpiel1.json
     ./games/TollesSpiel2.json
usw.
Habe wenig bis keine Erfahrung mit JavaScript oder WebDev im Allgemeinen kann also nicht sagen ob das einfach umsetzbar ist. Zum hinzufügen wäre es aus meiner Sicht aber einfacher, da so auch Konflikte mit git vorgebeugt werden könnten.
So sollte es auch einfacher sein eventuell weitere Atribute zu Einträgen hinzuzufügen.

**Comment by LauraWebdev** [comment]
Ich denke da war mal etwas, dass Javascript nicht dynamisch im Ordnersystem nachschauen kann.. aber eine universelle JSON Datei würde ich auch begrüßen, diese könnte man ja sogar als Api Endpoint anbieten

**Comment by letsgamedev** [comment]
Naja die Spiele sind ja so bereits im JSON Format. Es würde also aus meiner Sicht keine nennenswerte Vorteile bieten ausser dass ich die JSON einbinden müsste. Ich nutze das meißt direkt als js weil das einfach simpler ist^^
